name: Docker Image CI - Java 11
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 5 * *"
env:
  DOCKER_IMAGE_NAME: docker.io/ndscprm/geoserver
jobs:    
  build:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 1
      matrix:
        version: [2.24.2, 2.26.3, 2.26.4, 2.27.1, 2.27.2, 2.27.3]
        # os: [alpine, jammy]        
    steps:
    - name: Current DateTime
      id: datetime
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYYMMDD-HHmmss"
        
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
      uses: docker/build-push-action@v5.3.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # Path to the Dockerfile
        file: Dockerfile
        build-args: |
          JAVA_MAJOR_VERSION=11
          GEOSERVER_VERSION=${{ matrix.version }} 
        # Always attempt to pull all referenced images
        pull: true
        # Push is a shorthand for --output=type=registry
        push: true
        # List of tags
        tags: |
          ${{ env.DOCKER_IMAGE_NAME }}:${{ matrix.version }}-java11-${{ steps.datetime.outputs.time }}
          ${{ env.DOCKER_IMAGE_NAME }}:${{ matrix.version }}-java11
          ${{ env.DOCKER_IMAGE_NAME }}:${{ matrix.version }}
        cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:${{ matrix.version }}-java11-${{ steps.datetime.outputs.time }}
        cache-to: type=inline
        platforms: linux/amd64,linux/arm64
        
    - name: Analyze for critical and high CVEs
      id: docker-scout-cves
      # if: ${{ github.event_name != 'pull_request_target' }}
      uses: docker/scout-action@v1
      with:
        command: cves
        image: ${{ env.DOCKER_IMAGE_NAME }}:${{ matrix.version }}-java11-${{ steps.datetime.outputs.time }}
        sarif-file: sarif.output.json
        summary: true
    
    - name: Upload SARIF result
      id: upload-sarif
      # if: ${{ github.event_name != 'pull_request_target' }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: sarif.output.json
